#server
server:
  port: 8888
spring:
  profiles:
    active: dev
  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: rose-gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.addr}
        namespace: ${nacos.namespace}
    gateway:
      discovery:
        locator:
          # 让gateway通过服务发现组件找到其他的微服务
          enabled: false
      httpclient:
        connect-timeout: 45000
        response-timeout: 45000
      routes:
        - id: rose-content-server-route
          uri: lb://rose-content-server
          predicates:
            - Path=/rose-content-server/**
        - id: rose-login-server-route
          uri: lb://rose-login-server
          predicates:
            - Path=/rose-login-server/**
logging:
# 嫌日志太多就注掉
#  level:
#    org.springframework.cloud.gateway: trace
  config: classpath:logback.xml